### ISSUE TITLE
[PE-D][Tester C] Missing index number on a contact detail

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F10-3/tp#331] opened 2024-11-08 17:35 UTC
![image.png](https://raw.githubusercontent.com/jian7490/ped/main/files/8d1bb64a-7a74-460a-9744-92ce3477d454.png)

If I want to addnote for a person named `bca`, I will have to firstly use command `find bca` followed by a command `addnote 1 n/note1`. After this, the contact's list will be back to the full list, and I won't be able to locate the index of this person named `bca`. If I want to add multiple notes to him/her, I may need to keep using `find bca` and `addnote 1 n/someNote` to do this, which is troublesome. A nicer way is to show the index number on the detail part at right.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jian7490/ped#3

**Comment by joeltio** [comment] 2024-11-09 10:37
Duplicate of #366

**Closed by joeltio** 2024-11-09 10:37 UTC
Labels: type.feature-flaw
